name: Docker Pipeline

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-pipeline .

      - name: Run Tests Inside Docker
        run: docker run my-pipeline
